spring:
  application:
    name: api-gateway



eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/


server:
  port: 9999

zuul:
  #全部服务忽略敏感头(全部服务都可以传递cookie)
  sensitive-headers:
  routes:
    myProduct:
     path: /mypro/**
     serviceId: product
     sensitiveHeaders:
management:
  security:
    enabled: false
