
spring:
  application:
    name: order
  rabbitmq:
    host: 120.78.94.244
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://192.168.111.143:3306/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 120.78.94.244
    port: 6481
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
   test4
      
      
