spring:
  datasource:
    url: jdbc:mysql://192.168.111.144:3306/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 120.78.94.244
    port: 6481
